---
task: clm

# dataset name for loading from HF hub
dataset_name: null
# if dataset stored locally
dataset_dir: data/preprocessed

train_batch_size: 8
valid_batch_size: 8
weight_decay: 0.2
shuffle_buffer: 1_000
learning_rate: 5e-4
lr_scheduler_type: cosine
num_warmup_steps: 2_000
gradient_accumulation_steps: 1
gradient_checkpoint: false
num_train_epochs: 10
max_train_steps: 150_000
max_eval_steps: -1
seq_length: 1024
save_checkpoint_steps: 1000 # 15,000
logging_steps: 100