---
task: clm

dataset_name: null
# local test
dataset_dir: data/test_data   # @todo: update dataset directory

train_batch_size: 12
valid_batch_size: 12
weight_decay: 0.2
shuffle_buffer: 1_000
learning_rate: 5e-4
lr_scheduler_type: cosine
num_warmup_steps: 2_000
gradient_accumulation_steps: 1
gradient_checkpoint: false
num_train_epochs: 10
max_train_steps: 150_000
max_eval_steps: -1
seq_length: 1024
save_checkpoint_steps: 15_000
