---
task: codesearch

dataset_dir: data/csn
dataset_lang: python
load_data_from_disk: False

train_batch_size: 64
valid_batch_size: 64
test_batch_size: 1000

max_code_length: 128
max_query_length: 128

learning_rate: 5e-5
epochs: 5
patience: 2
