---
task: code2nl

dataset_dir: data/csn
dataset_lang: python
load_data_from_disk: False

train_batch_size: 64
valid_batch_size: 64
test_batch_size: 64

max_input_length: 128
max_output_length: 64

beam_size: 10
learning_rate: 5e-5
epochs: 5
patience: 2
