---
# dataset name for loading from HF hub
hf_user: martiwey
dataset_name: gh-java-methods-small-id-ft-train

task: api_call_completion     # api_call_completion | api_usage_completion
domain: id_all                # id_all | ood_all | ood_general | ood_security | ood_android | ood_web | ood_guava

train_batch_size: 6
valid_batch_size: 6
learning_rate: 5e-5
num_train_epochs: 5
weight_decay: 0.0
max_grad_norm: 1.0
logging_steps: 50
