---
hf_user: martiwey
dataset_name: gh-java-methods-small-id-ft-train

task: api-call-completion     # api-call-completion | api-usage-completion
domain: id-all                # id-all | ood-all | ood-general | ood-security | ood-android | ood-web | ood-guava

train_batch_size: 6
valid_batch_size: 6
learning_rate: 5e-5
num_train_epochs: 2
max_train_steps: 50000
eval_steps: 5000
weight_decay: 0.0
max_grad_norm: 1.0
logging_steps: 50
