---
hf_user: null
dataset_name: data/gh-java-methods-small-ood-test

task: call    # perplexity | code-completion | call | usage
domain: all   # all | general | security | android | web | guava

# HP for the api usage completion task
max_new_tokens: 30
do_sample: true
temperate: 0.2
top_p: 0.95
top_k: 0

batch_size: 16
