---
experiment: zero-shot         # zero-shot, naive, cl
evaluate: api_completion      # perplexity | token_completion | api_completion | api_usage_completion

# dataset name to load from HF hub
hf_user: martiwey
dataset_name: gh-java-methods-small-ood-test
domain: all

# HP for the api_usage_completion task
max_new_tokens: 30
do_sample: true
temperate: 0.2
top_p: 0.95
top_k: 0

batch_size: 16
