---
experiment: zero-shot   # zero-shot, naive, cl

hf_user: martiwey
dataset_name: gh-java-methods-small-ood-test

task: api-call-completion      # perplexity | token-completion | api-call-completion | api-usage-completion
domain: all                    # all | general | security | android | web | guava

# HP for the api-usage-completion task
max_new_tokens: 30
do_sample: true
temperate: 0.2
top_p: 0.95
top_k: 0

batch_size: 16
