---
task: mlm
mlm_probability: 0.15

# dataset names for loading from HF hub
train_dataset_name: martiwey/gh-java-methods-small-id-train
valid_dataset_name: martiwey/gh-java-methods-small-id-valid

train_batch_size: 12
valid_batch_size: 12
shuffle_buffer: 10000
mixed_precision: fp16
weight_decay: 0.1
learning_rate: 5e-4
lr_scheduler_type: cosine
num_warmup_steps: 750
gradient_accumulation_steps: 16
gradient_checkpointing: true
max_train_steps: 150000
max_eval_steps: -1
seq_length: 1024
save_checkpoint_steps: 15000
logging_steps: 100
resume_from_checkpoint: null