---
task: mlm

# dataset name for loading from HF hub
dataset_name: null
# if dataset stored locally
dataset_dir: data/preprocessed
resume_from_checkpoint: null

per_device_train_batch_size: 8
per_device_eval_batch_size: 8
mixed_precision: fp16
weight_decay: 0.2
learning_rate: 5e-4
lr_scheduler_type: cosine
num_warmup_steps: 750
gradient_accumulation_steps: 1
gradient_checkpoint: false
num_train_epochs: 10
max_train_steps: 150000
max_eval_steps: -1
seq_length: 1024
save_checkpoint_steps: 15000
logging_steps: 100