---
# dataset names for loading from HF hub
train_dataset_name: martiwey/gh-java-methods-small-id-train
valid_dataset_name: martiwey/gh-java-methods-small-id-valid

train_batch_size: 12
valid_batch_size: 12
shuffle_buffer: 10000
mixed_precision: fp16
weight_decay: 0.01          # 0.1 decoder, 0.01 encoder
learning_rate: 5e-6         # 5e-5 decoder, 5e-6 encoder
lr_scheduler_type: linear   # cosine decoder, linear encoder
num_warmup_steps: 10000
gradient_accumulation_steps: 8
gradient_checkpointing: false
num_train_epochs: 25
max_train_steps: 100000
max_eval_steps: -1
save_checkpoint_steps: 10000
logging_steps: 50
resume_from_checkpoint: null
mlm_probability: 0.15